name: Check Affected Files
description: This action checks the affected files by comparing the current commit with the previous commit.
inputs:
  commit_ref:
    description: The commit reference to compare against.
    required: false
    default: 'HEAD^1'
outputs:
  files:
    description: The list of affected files.
    value: ${{ steps.get_diff.outputs.files }}
runs:
  using: 'composite'
  steps:

    - name: Get affected files
      id: get_diff
      shell: bash
      run: |
        echo "Fetching affected files..."
        files=$(git diff --name-only ${{ inputs.commit_ref }} HEAD)
        echo "Affected files: $files"
        
        # Wrapping the multi-line output in a format for GitHub Actions
        echo "files<<EOF" >> $GITHUB_OUTPUT
        echo "$files" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
