name: Install dependencies
description: Perform npm install and cache node_modules

runs:
  using: composite
  steps:
    - name: Cache node_modules
      id: cache
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies if cache is missed.
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm clean-install