name: Install dependencies
description: Perform npm install and cache node_modules

runs:
  using: composite
  steps:
    - name: Cache node_modules
      id: cache
      uses: actions/cache@v4
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      shell: bash
      run: |
          if [ ! -d "node_modules" ]; then
            echo "Cache not found, installing dependencies..."
            npm clean-install
          else
            echo "Cache found!"
          fi