name: Install dependencies
description: Perform npm install and cache node_modules

runs:
  using: composite
  steps:
    - name: Cache node_modules
      id: cache
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies if cache is missed.
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm clean-install