name: Pull Request Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  is-renovate-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Actor
        id: check-actor
        run: |
          echo "isRenovateBot=$([[ '${{ github.actor }}' == 'renovate[bot]' || '${{ github.actor }}' == 'renovate-bot' ]] && echo 1 || echo 0)" >> $GITHUB_ENV

  test-renovate:
    name: Test Renovate PR
    needs: is-renovate-bot
    if: ${{ env.isRenovateBot }} == '1'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit test
        uses: ./.github/actions/tests/unit-test
        timeout-minutes: 20

  test-affected-pr:
    name: Test Affected PR
    needs: is-renovate-bot
    if: ${{ env.isRenovateBot }} == '0'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        