name: Pull Request Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  is-renovate-bot:
    name: "[Opened] Is Renovate Bot?"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      isRenovateBot: ${{ steps.check-actor.outputs.isRenovateBot }}
    steps:
      - name: Check Actor
        id: check-actor
        run: |
          if [[ '${{ github.actor }}' == 'renovate[bot]' || '${{ github.actor }}' == 'renovate-bot' ]]; then
            echo "::set-output name=isRenovateBot::1"
          else
            echo "::set-output name=isRenovateBot::0"
          fi

  test-renovate:
    name: "YES - Run all tests"
    needs: is-renovate-bot
    if: needs.is-renovate-bot.outputs.isRenovateBot == '1' 
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit test
        uses: ./.github/actions/tests/unit-test
        timeout-minutes: 20

  test-affected-pr:
    name: "NO - Run tests for affected projects"
    needs: is-renovate-bot
    if: needs.is-renovate-bot.outputs.isRenovateBot == '0'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo Message
        run: echo "Running tests for affected PR"
  
  check-affected-files:
    name: Check Affected files
    needs: is-renovate-bot
    if: needs.is-renovate-bot.outputs.isRenovateBot == '0'
    uses: ./.github/actions/files/check-affected

        